List = [
    'Demasiados clientes',
    'Dependencia en muy pocos clientes',
    'Creciente competencia',
    'Atendemos demasiados segmentos de mercado',
    'Desconocimiento de la competencia',
    'Baja rentabilidad',
    'Mercado poco fértil',
    'La empresa es demasiado pequeña',
    'Estamos más enfocados al producto que a las necesidades del cliente',
    'Debilidad ante la competencia',
    'Bajas ventas',
    'Dificultades de cobranza',
    'Negocio invalidado por el entorno',
    'Márgenes estrechos',
    'Nos hemos convertido en un competidor del montón',
    'Clientes insatisfechos',
    'Manejamos demasiados negocios',
    'Orientación al volumen',
    'Productos obsoletos',
    'Elevado número de quejas',
    'Nuestra propuesta al mercado se vuelve irrelevante',
    'Empresa con imagen pobre / desconocida',
    'Nuestra identidad no está alineada a nuestra propuesta al cliente',
    'Tenemos mala imagen en el mercado',
    'Dificultades familiares afectan el negocio',
    'Se ha perdido la confianza entre socios',
    'Demasiados conflictos / desunión',
    'Objetivos indefinidos o no compartidos',
    'La visión de los socios no es clara ni compartida',
    'No sabemos nuestros propósitos',
    'Hay problemas con la participación de familiares en el negocio',
    'Ya estoy cansado de no tener claro el camino',
    'Confusión en el manejo del dinero: sueldos, préstamos, etc.',
    'Desacuerdo en el concepto de negocio',
    'Diferencias entre socios',
    'Crecimiento demasiado rápido',
    'Crecimiento demasiado lento',
    'Carencia de equipo gerencial',
    'Baja capacidad administrativa',
    'Ceguera, sobreconfianza',
    'Excesiva centralización',
    'Demasiados proyectos a la vez',
    'Falta de coordinación entre departamentos',
    'Excesiva improvisación',
    'No hay trabajo en equipo',
    'Falta de consistencia en el avance',
    'Se cede ante la mediocridad  / falta de exigencia',
    'El rol de dueño no se ejerce con fuerza',
    'Falta desarrollo gerencial',
    'Estilo de mando ineficaz',
    'Vacío de poder',
    'Cambio frecuente de prioridades',
    'Lentitud en los cambios requeridos',
    'No hemos previsto cómo manejar la sucesión',
    'Se confunden los roles de dueño, directivo, empleado.',
    'Falta un líder claro y poderoso que dirija a la organización',
    'Rumbo perdido',
    'Problemas de relación con las autoridades',
    'Me falta capacidad directiva',
    'Nombramientos importantes por criterios familiares y afectivos',
    'Accionistas pasivos poco informados e involucrados',
    'Estructura de capital es una traba para crecer y atraer socios',
    'Los accionistas carecemos de un plan patrimonial',
    'Distribución pobre de dividendos',
    'Inquietudes no resueltas con relación al riesgo país',
    'Reuniones excesivas y/o inefectivas',
    'Estructura organizacional mal diseñada, inoperante',
    'Comunicación ineficaz',
    'Mal manejo del tiempo',
    'Mucha gente no domina los sistemas operativos',
    'Desánimo y baja moral',
    'No saber retener gente valiosa',
    'Descuido de la calidad',
    'Bajo nivel de servicio',
    'No hay evaluación objetiva del desempeño',
    'Delegación ineficaz',
    'Débil fuerza  de ventas',
    'Elevada rotación de personal',
    'El negocio es demasiado grande, organización rebasada',
    'Deficiencias en la contratación',
    'Conflictos laborales / intranquilidad',
    'Entregas tardías a clientes',
    'Personal excesivo',
    'No se cumplen internamente los compromisos',
    'Personal mal pagado',
    'Falta de capital',
    'Desaprovechamiento de recursos',
    'Equipos sub-utilizados',
    'Falta de liquidez',
    'Fallas de aprovisionamiento de proveedores',
    'Elevado punto de equilibrio',
    'Gastos fijos altos',
    'Inventarios desbalanceados / baja rotación',
    'Inversiones mal planeadas',
    'Elevados costos',
    'Tecnología obsoleta',
    'Equipo insuficiente o inadecuado',
    'Baja productividad',
    'Lentitud en nuestro proceso de transformación digital',
    'Indicadores desactualizados',
    'Limitada trazabilidad operativa',
    'Excesiva y costosa información que poco nos sirve',
    'No contamos con un ERP que nos dé el pulso del negocio',
    'Carecemos de un sistema de costeo ágil' 
]