'use client'
import './globals.css'
import "bootstrap/dist/css/bootstrap.min.css"
import { AuthProvider } from '../../context/authContext'
import ImportBootstrap from '../../components/ImportBootstrap'
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";

config.autoAddCss = false;

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ImportBootstrap /> 
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
